### ISSUE TITLE
The "Ru" and "En" Language Selectors are Mixed Up

### ISSUE THREAD

**Issue by Bradleykingz** [0xJacky/nginx-ui#135] opened 2023-06-24 16:56 UTC
**Describe the bug**
The "Ru" and "En" language options are switched up. Selecting "En" changes the language to Russian, and "Ru" changes it to English.

**To Reproduce**
1. Go to '#/login' (first language is Russian)
2. Click on dropdown, click on "Ru" (Language changes to English)
3. Click on "En" (Language changes to Russian)

**Expected behavior**
Language should start off as English, and clicking on "Ru" should change to Russian. Clicking on "En" should change language to English.

**Screenshots**
Language starts of as "En" but is actually "Ru"
![image](https://github.com/0xJacky/nginx-ui/assets/19578478/4196018d-2aa1-4179-b241-f00f9f33e816)

Switching language to "En" changes language to Russian.
![image](https://github.com/0xJacky/nginx-ui/assets/19578478/2e01edf5-6302-46fb-be71-c99af878bf4f)

**Comment by kcholoren** [comment] 2023-06-24 18:20
It was already reported https://github.com/0xJacky/nginx-ui/issues/134

**Comment by 0xJacky** [comment] 2023-06-27 14:32
This problem is strange, cause we can't reproduce it in our local machine, but recently we are working hard to implement the translation in a more efficient way, we hope this bug will be fixed in next beta version.

**Comment by 0xJacky** [comment] 2023-08-27 06:20
Fixed in 5cf11813e972541207bd4425e02ffa07abe8c232

**Closed by 0xJacky** 2023-08-27 06:20 UTC
Labels: bug
