### ISSUE TITLE
Nginx does not reload when adding a site, enabling a site, or disabling a site

### ISSUE THREAD

**Issue by sanvu88** [0xJacky/nginx-ui#222] opened 2023-12-06 08:53 UTC
**Describe the bug**

- Nginx does not reload when add a site, enable a site, or disable a site
- Using Nginx Control Menu to Reload and Restart Nginx also has no effect

**To Reproduce**

I tried both the pre-built binary version and the build from source and both failed. Binary download link and Source I used:

- https://github.com/0xJacky/nginx-ui/archive/refs/tags/v2.0.0-beta.5-patch.tar.gz
- https://github.com/0xJacky/nginx-ui/releases/download/v2.0.0-beta.5-patch/nginx-ui-linux-64.tar.gz

**Info:**
 - Server OS: Debian 12
 - Server Arch: x64
 - Nginx UI Version: v2.0.0-beta.5-patch
 - Your Browser: Chrome

**Comment by 0xJacky** [comment] 2023-12-06 09:43
Can you provide the logs?

**Comment by wienfuchs** [comment] 2023-12-06 09:46
This issue ouccurs also with me, since upgrade to v2.0.0-beta.5 - so it is probably located in that changes. No log access at the moment from my side, sorry.

**Comment by sanvu88** [comment] 2023-12-06 09:49
> Can you provide the logs?

When the operation all succeeded and there was no error log from Nginx.

**Comment by 0xJacky** [comment] 2023-12-06 09:52
ok, I will fix it as soon as possible.

**Comment by 0xJacky** [comment] 2023-12-06 10:47
I fixed in [7c6b4fe](https://github.com/0xJacky/nginx-ui/commit/7c6b4fec914534e0ea1c7734ab2198f474fcd276). It works fine in my docker container, can you test this version, as I'm not sure it can also work well in your environment.

**Comment by sanvu88** [comment] 2023-12-06 12:35
> I fixed in [7c6b4fe](https://github.com/0xJacky/nginx-ui/commit/7c6b4fec914534e0ea1c7734ab2198f474fcd276). It works fine in my docker container, can you test this version, as I'm not sure it can also work well in your environment.

I have tested your fix and the Reload command works fine when add, disable, and enable site. However, I discovered a new problem with the Nginx restart in the Nginx Control menu

![image](https://github.com/0xJacky/nginx-ui/assets/12091815/827840e7-5192-4131-b8ea-147cf37dc418)

To test I did the following. First I stopped Nginx

`systemctl stop nginx`

then used  Restart Nginx on menu

![image](https://github.com/0xJacky/nginx-ui/assets/12091815/19fc2bb0-e4f1-4f0b-92b2-2b9ccdefb065)

But, When I check Nginx's status it is actually inactive

![image](https://github.com/0xJacky/nginx-ui/assets/12091815/591d0e06-fd8f-41ee-9ae2-ffed4ae303ba)

Next I tried checking the listen port to see why Nginx UI reported Nginx running. Then I see that there is an Nginx process running and listening to port 80

`netstat -tupln`

![image](https://github.com/0xJacky/nginx-ui/assets/12091815/d851cf4b-d10b-42fc-ae24-76ed22ef688e)

This problem will not occur when I restart Nginx directly from the server.

**Comment by 0xJacky** [comment] 2023-12-06 13:15
In this verison, I use two separate commands to restart nginx.

https://github.com/0xJacky/nginx-ui/blob/7c6b4fec914534e0ea1c7734ab2198f474fcd276/internal/nginx/nginx.go#L59-L61

When you click the reload button in nginx-ui, it attempts to stop nginx whether it's running or not, that's why the error message appears if nginx is already stopped. To address this, I should check the running status of nginx before attempting to stop it.

The second problem is when starting a process without using systemtl (or services). I you use systemtl status to check the running status, it will always report inactive. To reproduce this, you can execute `nginx -s stop`, followed by `nginx`, and then using `systemctl status nginx` to check the status.

And you might notice that I use this method to restart nginx in the Line 59 to 61 in `internal/nginx/nginx.go`. To fix this issue, you can set a nginx restart command like `systemctl restart nginx` in your nginx-ui configuration file, app.ini. 

Since we have to support the environments without systemctl, we can't replace the default restart command with a systemctl command.

**Comment by 0xJacky** [comment] 2023-12-06 13:23
Maybe I should use start-stop-daemon[https://man7.org/linux/man-pages/man8/start-stop-daemon.8.html]

**Comment by sanvu88** [comment] 2023-12-06 13:52
yes, i tried use RestartCmd configuration and it worked perfectly. 

i also tried start-stop-daemon command

`start-stop-daemon --start --pidfile /var/run/nginx.pid --exec /usr/sbin/nginx`

then the result when using start-stop-daemon is the same as using nginx -s. And if using start-stop-daemon forces users to install everything by default and will not be able to customize the path of nginx binary or pid file location.

I think using app.ini configuration will be the perfect solution.

**Closed** 2023-12-06 14:57 UTC
Labels: bug, documentation
